Dva18
dvajs/dva pull request #2515
Opened 2024-05-06 09:37 UTC by jasonzhuang

升级react版本，在依赖react-dom的地方升级了用法，使用creatRoot来渲染

2024-05-06 09:44 UTC, sorrycc requested changes
1、不要改 code style
2、不要改版本号
3、peerDependencies 要兼容而不是替换

2024-05-07 09:07 UTC, sorrycc requested changes
做最小改动，不要做风格调整。

2024-05-07 09:07 UTC, sorrycc commented on package.json
> +}
1、去掉 repository
2、结尾得有空行

2024-05-07 09:07 UTC, sorrycc commented on .gitignore
> +.history/
不要加这个。

2024-05-07 09:07 UTC, sorrycc commented on packages/dva/src/index.js
> +export default function (opts = {}) {
不要做风格调整，应该是你本地的 prettier 和 dva 的 prettier 版本不一致。

2024-05-07 09:07 UTC, sorrycc commented on .prettierrc
> +  "semi": true
不要做调整。

2024-05-07 09:31 UTC, jasonzhuang commented on .gitignore
> +.history/
我先删掉。但实际上最好有这个说明，不然vscode有些装了这个插件的，会默认生成

2024-05-07 09:31 UTC, jasonzhuang commented on package.json
> +}
done

2024-05-07 11:34 UTC, jasonzhuang commented on packages/dva/src/index.js
> +export default function (opts = {}) {
done, 暂时把vscode上formatOnSave关闭了解决

2024-05-07 11:34 UTC, jasonzhuang commented on .prettierrc
> +  "semi": true
done

2024-05-10 02:06 UTC, sorrycc approved these changes

2024-05-10 02:07 UTC, merged

2024-05-10 02:10 UTC, sorrycc commented
Bumped dva@3.0.0-alpha.1